name: AIC
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip                             # keep pip in env
  # native packages
  - tesseract                       # OCR engine (binary)
  - poppler                         # required by pdf-to-image (future)
  - redis-py                        # async redis client
  - motor                           # async mongo driver
  - httpx
  - fastapi
  - uvicorn
  - pydantic
  - numpy                           # FAISS needs it
  # anything not on conda-forge:
  - pip:
      - openai
      - faiss-cpu                   # vector search
